openapi: 3.0.1
info:
  title: RestDocs to Swagger 변환 테스트
  description: Restdocs로 API 문서 작성 후 이를 Swagger로 변환하는 페이지
  version: 0.0.1-SNAPSHOT
servers:
- url: http://localhost:8080
tags: []
paths:
  /story:
    post:
      tags:
      - Story
      summary: 스토리 생성 API
      description: 스토리 생성 API
      operationId: story-controller-test/스토리_생성
      parameters:
      - name: Authorization
        in: header
        description: ACCESS TOKEN
        required: true
        schema:
          type: string
        example: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZXMiOltdLCJpYXQiOjE2Nzk0NzIzMTAsImV4cCI6MTY4MzA3MjMxMH0.z_oE-pzcvdIaUqLxULlfBZf6dadfq2btSLsSrhqvcvI
      requestBody:
        content:
          multipart/form-data;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/story1012374214'
            examples:
              story-controller-test/스토리_생성:
                value: "{\"contents\":\"스토리의 내용입니다.\",\"storyImage\":\"org.springframework.mock.web.MockMultipartFile@5444f1c3\"\
                  }"
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/story221479330'
              examples:
                story-controller-test/스토리_생성:
                  value: "{\"message\":\"성공\",\"code\":200,\"data\":{\"storyId\":1}}"
      security:
      - bearerAuthJWT: []
    patch:
      tags:
      - Story
      summary: 스토리 변경 API
      description: 스토리 변경 API
      operationId: story-controller-test/스토리_업데이트
      parameters:
      - name: Authorization
        in: header
        description: ACCESS TOKEN
        required: true
        schema:
          type: string
        example: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZXMiOltdLCJpYXQiOjE2Nzk0NzIzMTAsImV4cCI6MTY4MzA3MjMxMH0.z_oE-pzcvdIaUqLxULlfBZf6dadfq2btSLsSrhqvcvI
      requestBody:
        content:
          multipart/form-data;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/story-278565220'
            examples:
              story-controller-test/스토리_업데이트:
                value: "{\"storyId\":1,\"contents\":\"스토리의 내용이에요\",\"storyImage\"\
                  :\"org.springframework.mock.web.MockMultipartFile@cd93621\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/story221479330'
              examples:
                story-controller-test/스토리_업데이트:
                  value: "{\"message\":\"성공\",\"code\":200,\"data\":{\"storyId\":1}}"
      security:
      - bearerAuthJWT: []
  /story/all:
    get:
      tags:
      - Story
      summary: 스토리 전체 조회 API
      description: 스토리 전체 조회 API
      operationId: story-controller-test/스토리_전체조회
      parameters:
      - name: Authorization
        in: header
        description: 요청자의 JWT
        required: true
        schema:
          type: string
        example: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZXMiOltdLCJpYXQiOjE2Nzk0NzIzMTAsImV4cCI6MTY4MzA3MjMxMH0.z_oE-pzcvdIaUqLxULlfBZf6dadfq2btSLsSrhqvcvI
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/story-all876884235'
              examples:
                story-controller-test/스토리_전체조회:
                  value: "{\"message\":\"성공\",\"code\":200,\"data\":[{\"id\":1,\"\
                    storyImageUrl\":\"http://1\"},{\"id\":2,\"storyImageUrl\":\"http://2\"\
                    }]}"
      security:
      - bearerAuthJWT: []
  /user/profile:
    patch:
      tags:
      - UserProfile
      summary: 프로필 변경 API
      description: 프로필 변경 API
      operationId: user-profile-controller-test/프로필_업데이트
      parameters:
      - name: Authorization
        in: header
        description: JWT
        required: true
        schema:
          type: string
        example: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZXMiOltdLCJpYXQiOjE2Nzk0NzIzMTAsImV4cCI6MTY4MzA3MjMxMH0.z_oE-pzcvdIaUqLxULlfBZf6dadfq2btSLsSrhqvcvI
      requestBody:
        content:
          multipart/form-data;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/user-profile-1030560250'
            examples:
              user-profile-controller-test/프로필_업데이트:
                value: "{\"gender\":\"MAN\",\"wantedAnimal\":\"고양이상\",\"nickname\"\
                  :\"유저닉네임\",\"mbti\":\"INTP\",\"animal\":\"고양이상\",\"location\":\"\
                  강동구\",\"profileImage\":\"org.springframework.mock.web.MockMultipartFile@6a1d1467\"\
                  ,\"smokingStatus\":false,\"job\":\"대학생이에요\",\"age\":25,\"height\"\
                  :175,\"selfDescription\":\"안녕하세요 자기소개입니다.\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/user-profile-748640380'
              examples:
                user-profile-controller-test/프로필_업데이트:
                  value: "{\"message\":\"성공\",\"code\":200,\"data\":{\"userId\":1}}"
      security:
      - bearerAuthJWT: []
  /user/{userId}:
    get:
      tags:
      - UserProfile
      summary: 유저프로필 조회 API
      description: 유저프로필 조회 API
      operationId: user-profile-controller-test/프로필_조회
      parameters:
      - name: userId
        in: path
        description: 대상 유저의Id
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: 요청보낸 사람 ACCESS TOKEN
        required: true
        schema:
          type: string
        example: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZXMiOltdLCJpYXQiOjE2Nzk0NzIzMTAsImV4cCI6MTY4MzA3MjMxMH0.z_oE-pzcvdIaUqLxULlfBZf6dadfq2btSLsSrhqvcvI
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/user-userId23762074'
              examples:
                user-profile-controller-test/프로필_조회:
                  value: "{\"message\":\"성공\",\"code\":200,\"data\":{\"nickname\"\
                    :\"오어어엉\",\"profileImageUrls\":[\"https:/sdg\",\"https:/asgd\"\
                    ],\"gender\":\"WOMAN\",\"age\":18,\"height\":167,\"job\":\"모름\"\
                    ,\"location\":\"NOWON\",\"selfDescription\":\"안녕하세요\",\"smokingStatus\"\
                    :false,\"mbti\":\"INTP\",\"animalType\":\"DEER\",\"longitude\"\
                    :112.125,\"latitude\":135323.235}}"
      security:
      - bearerAuthJWT: []
  /user/profile/all:
    get:
      tags:
      - UserProfile
      summary: 프로필 전체 조회 API
      description: 프로필 전체 조회 API
      operationId: user-profile-controller-test/프로필_전체조회
      parameters:
      - name: Authorization
        in: header
        description: 요청자의 JWT
        required: true
        schema:
          type: string
        example: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZXMiOltdLCJpYXQiOjE2Nzk0NzIzMTAsImV4cCI6MTY4MzA3MjMxMH0.z_oE-pzcvdIaUqLxULlfBZf6dadfq2btSLsSrhqvcvI
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/user-profile-all-193200887'
              examples:
                user-profile-controller-test/프로필_전체조회:
                  value: "{\"message\":\"성공\",\"code\":200,\"data\":[{\"profileId\"\
                    :1,\"nickname\":\"김성지1\",\"gender\":\"MAN\",\"age\":25,\"height\"\
                    :175,\"profileImageUrl\":\"http://\",\"location\":\"GANDONG\"\
                    ,\"animalType\":\"CAT\",\"longitude\":2153.23,\"latitude\":23.42},{\"\
                    profileId\":2,\"nickname\":\"김성지2\",\"gender\":\"WOMAN\",\"age\"\
                    :25,\"height\":175,\"profileImageUrl\":\"http://\",\"location\"\
                    :\"GANGBUK\",\"animalType\":\"DOG\",\"longitude\":23463.34,\"\
                    latitude\":1544.32}]}"
      security:
      - bearerAuthJWT: []
components:
  schemas:
    user-userId23762074:
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          type: object
          properties:
            gender:
              type: string
              description: 프로필 닉네임
            profileImageUrls:
              type: array
              description: 프로필 닉네임
              items:
                oneOf:
                - type: object
                - type: boolean
                - type: string
                - type: number
            latitude:
              type: number
              description: 경도
            animalType:
              type: string
              description: 프로필 닉네임
            selfDescription:
              type: string
              description: 프로필 닉네임
            nickname:
              type: string
              description: 프로필 닉네임
            mbti:
              type: string
              description: 프로필 닉네임
            location:
              type: string
              description: 프로필 닉네임
            smokingStatus:
              type: boolean
              description: 프로필 닉네임
            job:
              type: string
              description: 프로필 닉네임
            age:
              type: number
              description: 프로필 닉네임
            longitude:
              type: number
              description: 위도
            height:
              type: number
              description: 프로필 닉네임
        message:
          type: string
          description: 결과 메시지
    story1012374214:
      type: object
      properties:
        contents:
          type: string
          description: 스토리 내용
        storyImage:
          type: string
          description: 스토리 이미지
    story221479330:
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          type: object
          properties:
            storyId:
              type: number
              description: 스토리 id
        message:
          type: string
          description: 메시지
    user-profile-all-193200887:
      type: object
      properties:
        code:
          type: number
          description: 응답코드
        data:
          type: array
          items:
            type: object
            properties:
              gender:
                type: string
                description: 유저의 성별
              profileId:
                type: number
                description: 유저의 프로파일 ID
              latitude:
                type: number
                description: 유저의 위도
              animalType:
                type: string
                description: 유저의 동물상
              nickname:
                type: string
                description: 유저의 닉네임
              location:
                type: string
                description: 유저의 지역
              profileImageUrl:
                type: string
                description: 유저의 프로필이미지 URL
              age:
                type: number
                description: 유저의 나이
              longitude:
                type: number
                description: 유저의 경도
              height:
                type: number
                description: 유저의 키
        message:
          type: string
          description: 메시지
    user-profile-1030560250:
      type: object
      properties:
        gender:
          type: string
          description: 성별
        wantedAnimal:
          type: string
          description: 원하는 동물상
        nickname:
          type: string
          description: 유저닉네임
        animal:
          type: string
          description: 유저의 동물상
        mbti:
          type: string
          description: mbti
        location:
          type: string
          description: 사는 곳
        profileImage:
          type: string
          description: 프로필 이미지파일
        job:
          type: string
          description: 직업
        smokingStatus:
          type: boolean
          description: 흡연여부
        age:
          type: number
          description: 나이
        selfDescription:
          type: string
          description: 자기소개
        height:
          type: number
          description: 키
    user-profile-748640380:
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          type: object
          properties:
            userId:
              type: number
              description: 유저의 프로필 id
        message:
          type: string
          description: 메시지
    story-278565220:
      type: object
      properties:
        storyId:
          type: number
          description: 스토리 ID
        contents:
          type: string
          description: 내용
        storyImage:
          type: string
          description: 스토리 이미지
    story-all876884235:
      type: object
      properties:
        code:
          type: number
          description: 응답코드
        data:
          type: array
          items:
            type: object
            properties:
              storyImageUrl:
                type: string
                description: 스토리 이미지 URL
              id:
                type: number
                description: 스토리 ID
        message:
          type: string
          description: 메시지
  securitySchemes:
    bearerAuthJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
