openapi: 3.0.1
info:
  description: Spring REST Docs with SwaggerUI.
  title: restdocs-swagger API Documentation
  version: 0.0.1
servers:
- url: http://localhost:8080
paths: {}
components:
  schemas: {}

